version: '3'

services:
  react-ts:
    build: ./react-app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    
  go:
    build: ./go-app
    ports:
      - '8000:8000'
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0
    volumes:
      - './db/data:/var/lib/mysql'
      - './db/my.cnf:/etc/mysql/conf.d/my.cnf'
    # MYSQL_ROOT_PASSWORDのみをenvファイルで設定
    environment:
      MYSQL_ROOT_USER: ${ROOTUSER}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      TZ: "Asia/Tokyo"
    env_file:
      - .env
    ports:
      - '3306:3306'